spring:
  application:
    name: ShimmerShine
  profiles:
    active: dev  # ✅ Correct key here
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/
